version: '3.9'

services:
  db:
    container_name: service_db
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "2345:5432"

  mongo:
    container_name: mongo_db
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27016:27017"